version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    restart: always
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - nest_rmq_unack_net
networks:
  nest_rmq_unack_net:
    driver: bridge
